import { TIME_SLOTS } from '../data/constants';
import { format } from 'date-fns';

export default function EndorsementDetail({ endorsement, onClose, showPrint = false, onPrint }) {
  const timeSlot = TIME_SLOTS.find((s) => s.id === endorsement.timeSlot);

  const handlePrint = () => {
    if (onPrint) {
      onPrint();
      return;
    }

    const formatTime = (time) => {
      if (!time) return '';
      const [hours] = time.split(':');
      const h = parseInt(hours);
      const ampm = h >= 12 ? 'PM' : 'AM';
      const displayHour = h > 12 ? h - 12 : h === 0 ? 12 : h;
      return `${displayHour}:00 ${ampm}`;
    };

    const duration = endorsement.timeFrom && endorsement.timeTo
      ? parseInt(endorsement.timeTo.split(':')[0]) - parseInt(endorsement.timeFrom.split(':')[0])
      : 1;

    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Lesson Plan - ${endorsement.studentName}</title>
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            line-height: 1.6;
          }
          .header {
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 20px;
            margin-bottom: 30px;
          }
          .header h1 {
            color: #2563eb;
            margin: 0 0 10px 0;
          }
          .header p {
            color: #666;
            margin: 5px 0;
          }
          .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
            margin-bottom: 30px;
            background: #f8fafc;
            padding: 20px;
            border-radius: 8px;
          }
          .info-item label {
            font-weight: 600;
            color: #374151;
            display: block;
            margin-bottom: 4px;
          }
          .info-item span {
            color: #1e293b;
          }
          .section {
            margin-bottom: 25px;
          }
          .section h2 {
            color: #2563eb;
            font-size: 1.1rem;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 8px;
            margin-bottom: 15px;
          }
          .section-content {
            white-space: pre-wrap;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            color: #666;
            font-size: 0.9rem;
          }
          @media print {
            body { padding: 20px; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>ICAN Academy Lesson Plan</h1>
          <p>Substitute Teacher Guide</p>
        </div>

        <div class="info-grid">
          <div class="info-item">
            <label>Date</label>
            <span>${format(new Date(endorsement.date), 'EEEE, MMMM d, yyyy')}</span>
          </div>
          <div class="info-item">
            <label>Time</label>
            <span>${formatTime(endorsement.timeFrom)} - ${formatTime(endorsement.timeTo)} (${duration} hour${duration > 1 ? 's' : ''})</span>
          </div>
          <div class="info-item">
            <label>Student</label>
            <span>${endorsement.studentName}</span>
          </div>
          <div class="info-item">
            <label>Class Type</label>
            <span>${endorsement.classType}</span>
          </div>
          <div class="info-item">
            <label>Book/Material</label>
            <span>${endorsement.bookMaterial}</span>
          </div>
          <div class="info-item">
            <label>Absent Teacher</label>
            <span>${endorsement.absentTeacherName}</span>
          </div>
        </div>

        <div class="section">
          <h2>Last Lesson Covered</h2>
          <div class="section-content">${endorsement.lastLesson}</div>
        </div>

        <div class="section">
          <h2>Today's Lesson</h2>
          <div class="section-content">${endorsement.nextLesson}</div>
        </div>

        <div class="section">
          <h2>Lesson Plan</h2>
          <div class="section-content">${endorsement.aiSummary}</div>
        </div>

        ${endorsement.homework ? `
        <div class="section">
          <h2>Homework</h2>
          <div class="section-content">${endorsement.homework}</div>
        </div>
        ` : ''}

        ${endorsement.notes ? `
        <div class="section">
          <h2>Additional Notes</h2>
          <div class="section-content">${endorsement.notes}</div>
        </div>
        ` : ''}

        <div class="footer">
          Generated by ICAN Teacher Endorsement System
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="endorsement-detail-overlay" onClick={onClose}>
      <div className="endorsement-detail" onClick={(e) => e.stopPropagation()}>
        <button className="close-btn" onClick={onClose}>
          &times;
        </button>

        <div className="detail-header">
          <h2>Class Endorsement</h2>
          <div className={`detail-status ${endorsement.finalized ? 'finalized' : 'draft'}`}>
            {endorsement.finalized ? 'Finalized' : 'Draft'}
          </div>
        </div>

        <div className="detail-section">
          <div className="detail-row">
            <div className="detail-item">
              <label>Date:</label>
              <span>{format(new Date(endorsement.date), 'MMMM d, yyyy')}</span>
            </div>
            <div className="detail-item">
              <label>Time:</label>
              <span>{timeSlot?.label || endorsement.timeSlot}</span>
            </div>
          </div>
        </div>

        <div className="detail-section highlight">
          <div className="detail-item">
            <label>Student:</label>
            <span className="student-name">{endorsement.studentName}</span>
          </div>
          <div className="detail-item">
            <label>Class Type:</label>
            <span>{endorsement.classType}</span>
          </div>
          <div className="detail-item">
            <label>Book/Material:</label>
            <span>{endorsement.bookMaterial}</span>
          </div>
          <div className="detail-item">
            <label>Last Lesson Covered:</label>
            <span>{endorsement.lastLesson}</span>
          </div>
        </div>

        <div className="detail-section">
          <h3>AI Summary</h3>
          <p className="detail-content">{endorsement.aiSummary || 'Not provided'}</p>
        </div>

        <div className="detail-section">
          <h3>Next Lesson</h3>
          <p className="detail-content important">{endorsement.nextLesson || 'Not provided'}</p>
        </div>

        <div className="detail-section">
          <h3>Homework</h3>
          <p className="detail-content">{endorsement.homework || 'Not provided'}</p>
        </div>

        {endorsement.notes && (
          <div className="detail-section notes">
            <h3>Teacher Notes for Substitute</h3>
            <p className="detail-content">{endorsement.notes}</p>
          </div>
        )}

        <div className="detail-footer">
          <div className="detail-footer-info">
            <p>
              Submitted by: <strong>{endorsement.absentTeacherName}</strong>
            </p>
            <p className="timestamp">
              {endorsement.finalized ? 'Finalized' : 'Last updated'} on{' '}
              {format(new Date(endorsement.updatedAt), 'MMM d, yyyy h:mm a')}
            </p>
          </div>
          <button className="print-btn" onClick={handlePrint}>
            Print / Save PDF
          </button>
        </div>
      </div>
    </div>
  );
}
